### ISSUE TITLE
Figure out why JDK10,11 fail tests

### ISSUE THREAD

**Issue by danielcompton** [xeqi/peridot#47]
Looks like something related to parsing the version number.

https://travis-ci.org/xeqi/peridot/builds/385901040

https://github.com/xeqi/peridot/blob/master/test/peridot/test/multipart.clj#L10-L14

```
Exception in thread "main" java.lang.NullPointerException, compiling:(multipart.clj:10:3)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3463)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:408)
...
Caused by: java.lang.NullPointerException
	at clojure.lang.Numbers.ops(Numbers.java:942)
	at clojure.lang.Numbers.lte(Numbers.java:223)
	at clojure.lang.Numbers.lte(Numbers.java:3719)
	at peridot.test.multipart$fn__3469.invoke(multipart.clj:14)
```

**Comment by danielcompton** [comment]
Fixed in https://github.com/xeqi/peridot/commit/5ae0d3fae5f7d078d603c9043545cf613f47e127.
